### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by itsmeduncan** [decioferreira/omniauth-linkedin-oauth2#30]
What is the status of this project? There are 5 open pull requests, at least one of which will stop people from using this gem in Rails 5.

**Comment by decioferreira** [comment]
I haven't been actively maintaining this project, since I haven't built any production application on ruby/rails for more that 2 years now. And don't currently work in any application that integrates with LinkedIn. @heythisisnate is also a owner of the gem.

Any help for maintaining this gem is welcome.
